# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tankinfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
import sqlite3

class Ui_Form_tank(object):

    def add(self):
        enemyTankHealth = self.textEdit.toPlainText()
        ourTankHealth = self.textEdit_2.toPlainText()
        power = self.textEdit_3.toPlainText()
        enemyDamage = self.textEdit_4.toPlainText()
        playerDamage = self.textEdit_5.toPlainText()

        db = sqlite3.connect("tank.db")

        db.execute(""" INSERT INTO tank1(enemyTankHealth, ourTankHealth, power, enemyDamage, playerDamage) VALUES(?,?,?,?,?) """,(enemyTankHealth, ourTankHealth, power, enemyDamage, playerDamage))
        db.commit()

        self.load()


    def load(self):
        db = sqlite3.connect("tank.db")
        sql = """ SELECT * FROM tank1 """
        result = db.execute(sql)
        self.tableWidget.setRowCount(0)

        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))


    def delete(self):
        db = sqlite3.connect("snake.db")
        sql = """ SELECT * FROM tank1 """
        result = db.execute(sql)

        for row in enumerate(result):
            if row[0] == self.tableWidget.currentRow():
                data = row[1]
                enemyTankHealth = data[0]
                ourTankHealth = data[1]
                power = data[2]
                enemyDamage = data[3]
                playerDamage = data[4]

                db.execute(""" DELETE FROM tank1 WHERE enemyTankHealth = ? AND ourTankHealth = ? AND power = ? AND enemyDamage = ? AND playerDamage = ?""",(enemyTankHealth, ourTankHealth, power, enemyDamage, playerDamage))
                db.commit()
                self.load()


    def update(self):

        db = sqlite3.connect("tank.db")
        sql = """SELECT * FROM tank1"""
        cursor = db.cursor()
        result = cursor.execute(sql)

        y_enemyTankHealth = self.textEdit.toPlainText()
        y_ourTankHealth = self.textEdit_2.toPlainText()
        y_power = self.textEdit_3.toPlainText()
        y_enemyDamage = self.textEdit_4.toPlainText()
        y_playerDamage = self.textEdit_5.toPlainText()

        for row in enumerate(result):
            if row[0] == self.tableWidget.currentRow():
                data = row[1]
                enemyTankHealth = data[0]
                ourTankHealth = data[1]
                power = data[2]
                enemyDamage = data[3]
                playerDamage = data[4]

                cursor.execute('''UPDATE tank1 SET enemyTankHealth = ?, ourTankHealth = ?, power = ?, enemyDamage = ?, playerDamage = ?, WHERE enemyTankHealth = ?, ourTankHealth = ?, power = ?, enemyDamage = ?, playerDamage = ?''',
                               (y_enemyTankHealth, y_ourTankHealth, y_power, y_enemyDamage, y_playerDamage, enemyTankHealth, ourTankHealth, power, enemyDamage, playerDamage))
                db.commit()
                self.load()


    def Clicked(self):
        db = sqlite3.connect("tank.db")
        sql = """SELECT * FROM tank1"""
        cursor = db.cursor()
        result = cursor.execute(sql)
        for row in enumerate(result):
            if row[0] == self.tableWidget.currentRow():
                data = row[1]
                enemyTankHealth = data[0]
                ourTankHealth = data[1]
                power = data[2]
                enemyDamage = data[3]
                playerDamage = data[4]
                self.textEdit.setText(str(enemyTankHealth))
                self.textEdit_2.setText(str(ourTankHealth))
                self.textEdit_3.setText(str(power))
                self.textEdit_4.setText(str(enemyDamage))
                self.textEdit_5.setText(str(playerDamage))


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(755, 489)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 761, 491))
        self.frame.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 30, 181, 21))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(550, 30, 81, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"border: 3px solid #00007f;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(70, 70, 211);\n"
"border-radius:10px;\n"
"border: 3px solid #4646d3;\n"
"color:white\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.add)

        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 200, 161, 21))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 150, 101, 21))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 100, 81, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"border: 3px solid #00007f;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#339999;\n"
"border-radius:10px;\n"
"border: 3px solid #4646d3;\n"
"color:white\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.load)

        self.textEdit_4 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_4.setGeometry(QtCore.QRect(240, 250, 201, 31))
        self.textEdit_4.setStyleSheet("border-radius:10px;\n"
"border: 3px solid #00007f;\n"
"")
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_2.setGeometry(QtCore.QRect(240, 80, 201, 31))
        self.textEdit_2.setStyleSheet("border-radius:10px;\n"
"border: 3px solid #00007f;\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(120, 310, 521, 171))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.clicked.connect(self.Clicked)

        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(240, 20, 201, 31))
        self.textEdit.setStyleSheet("border-radius:10px;\n"
"border: 3px solid #00007f;\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_5 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_5.setGeometry(QtCore.QRect(240, 190, 201, 31))
        self.textEdit_5.setStyleSheet("border-radius:10px;\n"
"border: 3px solid #00007f;\n"
"")
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 260, 161, 21))
        self.label_5.setObjectName("label_5")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_3.setGeometry(QtCore.QRect(240, 140, 201, 31))
        self.textEdit_3.setStyleSheet("border-radius:10px;\n"
"border: 3px solid #00007f;\n"
"")
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 170, 81, 41))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"border: 3px solid #00007f;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(32, 98, 0);\n"
"border-radius:10px;\n"
"border: 3px solid #4646d3;\n"
"color:white\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.delete)


        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 161, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 240, 81, 41))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"border: 3px solid #00007f;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(121, 60, 90);\n"
"border-radius:10px;\n"
"border: 3px solid #4646d3;\n"
"color:white\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.update)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Enemy Tank Health</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Add"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Enemy Damage</span></p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Power</span></p><p><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("Form", "Display"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "enemyTankHealth"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "ourTankHealth"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "power"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "enemyDamage"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "playerDamage"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Player Damage</span></p><p><br/></p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "Delete"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Our Tank Health</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Form", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_tank()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
